# Generated by Django 5.1 on 2024-09-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='static/img/no-image.jpg', upload_to='product/'),
        ),
    ]
