# Generated by Django 5.1 on 2024-09-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
