# Generated by Django 5.1 on 2024-09-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_system', '0002_alter_customuserprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
