# Generated by Django 5.1 on 2024-09-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_system', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
